"""Google Dorking URL generator for phone number OSINT.

Generates targeted search URLs for social media platforms, forums, and
paste sites to discover digital footprints linked to a phone number.
"""

from urllib.parse import quote_plus

# Platforms and their dork templates.
# Each entry: (platform_name, dork_type, url_template)
# {number} is replaced with the normalized phone number.
DORK_TEMPLATES: list[tuple[str, str, str]] = [
    # Site-specific exact match
    ("facebook", "site_specific", 'https://www.google.com/search?q="{number}"+site:facebook.com'),
    ("linkedin", "site_specific", 'https://www.google.com/search?q="{number}"+site:linkedin.com'),
    ("instagram", "site_specific", 'https://www.google.com/search?q="{number}"+site:instagram.com'),
    ("twitter", "site_specific", 'https://www.google.com/search?q="{number}"+site:twitter.com'),
    ("tiktok", "site_specific", 'https://www.google.com/search?q="{number}"+site:tiktok.com'),
    ("pastebin", "site_specific", 'https://www.google.com/search?q="{number}"+site:pastebin.com'),
    # Arabic forums
    ("arabic_forums", "site_specific", 'https://www.google.com/search?q="{number}"+site:forums.arabsgate.com'),
    ("arabic_forums", "site_specific", 'https://www.google.com/search?q="{number}"+site:montada.echoroukonline.com'),
    # Exact match (no site restriction)
    ("general", "exact_match", 'https://www.google.com/search?q="{number}"'),
    # Partial match (last 7 digits, useful for local format)
    ("general", "partial_match", 'https://www.google.com/search?q="{short_number}"'),
    # WhatsApp check
    ("whatsapp", "exact_match", "https://wa.me/{raw_digits}"),
    # Truecaller lookup
    ("truecaller", "exact_match", "https://www.truecaller.com/search/eg/{local_number}"),
]


def generate_dorks(normalized_number: str) -> list[dict[str, str]]:
    """Generate dorking URLs for the given E.164 phone number.

    Returns a list of dicts with keys: platform, dork_type, url, phone_number.
    """
    raw_digits = normalized_number.lstrip("+")
    local_number = "0" + raw_digits[2:] if raw_digits.startswith("20") else raw_digits
    short_number = raw_digits[-7:]

    results: list[dict[str, str]] = []
    for platform, dork_type, template in DORK_TEMPLATES:
        url = template.format(
            number=normalized_number,
            raw_digits=raw_digits,
            local_number=local_number,
            short_number=short_number,
        )
        results.append({
            "platform": platform,
            "dork_type": dork_type,
            "url": url,
            "phone_number": normalized_number,
        })
    return results


def format_dorks_text(dorks: list[dict[str, str]]) -> str:
    """Format dork results as human-readable text for dorks.txt."""
    lines = [
        f"# Google Dorking URLs for {dorks[0]['phone_number'] if dorks else 'N/A'}",
        f"# Generated by OSINT Investigation Toolkit",
        f"# Total URLs: {len(dorks)}",
        "",
    ]
    current_platform = ""
    for dork in dorks:
        if dork["platform"] != current_platform:
            current_platform = dork["platform"]
            lines.append(f"## {current_platform.upper()}")
        lines.append(f"  [{dork['dork_type']}] {dork['url']}")
        lines.append("")
    return "\n".join(lines)
