"""Dual-output report writer: JSON + Markdown (with Arabic section headers).

Produces both machine-readable JSON and human-readable Markdown reports
for every scan operation (FR-009a).
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_json_report(data: dict[str, Any], output_path: Path) -> Path:
    """Write a JSON report to *output_path* and return the path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
    return output_path


def write_markdown_report(data: dict[str, Any], output_path: Path) -> Path:
    """Write a Markdown report with Arabic section headers to *output_path*."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    phone = data.get("phone_number", "N/A")
    ts = data.get("scan_timestamp", _now_iso())
    line_type = data.get("line_type", "unknown")
    carrier = data.get("carrier", "N/A")
    country = data.get("country", "EG")
    is_voip = data.get("is_voip", False)
    scanners_run = data.get("scanners_run", [])
    scanners_skipped = data.get("scanners_skipped", [])
    dorks_generated = data.get("dorks_generated", 0)
    evidence_dir = data.get("evidence_dir", "N/A")

    lines = [
        f"# تقرير الاستطلاع — Reconnaissance Report",
        f"",
        f"**رقم الهاتف / Phone Number**: `{phone}`",
        f"**التاريخ / Timestamp**: {ts}",
        f"",
        f"---",
        f"",
        f"## معلومات الخط — Line Information",
        f"",
        f"| الحقل / Field | القيمة / Value |",
        f"|---------------|----------------|",
        f"| نوع الخط / Line Type | {line_type} |",
        f"| شركة الاتصالات / Carrier | {carrier} |",
        f"| رمز الدولة / Country | {country} |",
        f"| VoIP | {'نعم / Yes' if is_voip else 'لا / No'} |",
        f"",
        f"## الماسحات — Scanners",
        f"",
        f"**تم التشغيل / Run**: {', '.join(scanners_run) if scanners_run else 'None'}",
        f"",
        f"**تم التخطي / Skipped**: {', '.join(scanners_skipped) if scanners_skipped else 'None'}",
        f"",
        f"## روابط البحث — Dorking URLs",
        f"",
        f"**عدد الروابط / URLs Generated**: {dorks_generated}",
        f"",
        f"## الأدلة — Evidence",
        f"",
        f"**مجلد الأدلة / Evidence Directory**: `{evidence_dir}`",
        f"",
        f"---",
        f"",
        f"*تم الإنشاء تلقائيًا بواسطة مجموعة أدوات OSINT*",
        f"*Auto-generated by OSINT Investigation Toolkit*",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def write_dual_report(data: dict[str, Any], directory: Path, basename: str = "report") -> tuple[Path, Path]:
    """Write both JSON and Markdown reports. Returns (json_path, md_path)."""
    json_path = write_json_report(data, directory / f"{basename}.json")
    md_path = write_markdown_report(data, directory / f"{basename}.md")
    return json_path, md_path
